---
- job_name: journal
  journal:
    json: false
    max_age: 12h
    labels:
      job: systemd-journal
    path: "${JOURNAL_PATH}"
  relabel_configs:
    - source_labels:
        - __journal__systemd_unit
      target_label: unit
    - source_labels:
        - __journal__hostname
      target_label: nodename
    - source_labels:
        - __journal_syslog_identifier
      target_label: syslog_identifier
    - source_labels:
        - __journal_container_name
      target_label: container_name
